{
 "title": "University API",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "HTTP запросы в секунду",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total[1m])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Среднее время ответа (секунды)",
   "type": "timeseries",
   "gridPos": { "x": 8, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "avg latency"
    }
   ]
  },
  {
   "title": "Ошибки 5xx в секунду",
   "type": "timeseries",
   "gridPos": { "x": 16, "y": 0, "w": 8, "h": 8 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{code=~\"5..\"}[1m])",
     "legendFormat": "5xx errors"
    }
   ]
  }
 ]
}